### ISSUE TITLE
Can I use this eye in the footer ?

### ISSUE THREAD

**Issue by sgwk** [jfmdev/jqEye#2]
I want to see this eye in the footer of the page , but if the content exceeds the height of the browser , It does not follow the mouse properly .
Is there a solution?
I would appreciate your help.

https://jsfiddle.net/sgwk/2uhxt8ug/1/

**Comment by jfmdev** [comment]
Hi! Thank you for notify me about that bug you found. Today I'm going to make a new commit, with a new version fixing it.
In the meantime, I have fixed the code that you sent me: https://jsfiddle.net/2uhxt8ug/2/

**Comment by sgwk** [comment]
Thank you so much for your plugin and assistance!
