### ISSUE TITLE
Step 3

### ISSUE THREAD

**Issue by willbrett-design** [jfmdev/jqEye#3]
Hey there, 

Im not quite sure what to do with step 3? Where do I put this bit of code? 

Thanks

**Comment by willbrett-design** [comment]
I've now copied from the advanced html into my code. The eyes are showing but not following the mouse and I can't figure out why. 

This is in the header:

```
 <script type="text/javascript" src="/js/jqeyes.js"></script>
        <script type="text/javascript" src="/js/jqeyes.min.js"></script>
        <script type="text/javascript">
            jQuery(document).ready(function() {
                jQuery("#circular div.pupil").jqEye({shape: "circle", radius:12});
            });
        </script>
```

This is in the body:

```
  <div id="circular" class="eyes">
                        <div class="left_eye">
                            <div class="pupil"></div>
                        </div>
                        <div class="right_eye">
                            <div class="pupil"></div>
                        </div>
                    </div>
```

and this is in the stylesheet:

```
div.eyes {
    width: 160px;
    height: 60px;
    margin: 0 auto;
    position: relative;
    margin-bottom: 40px;
}

div.left_eye,
div.right_eye {
    width: 60px;
    height: 60px;
    position: absolute;
    background-repeat: no-repeat;
    background-position: center center;                  
}

div.left_eye {
    left: 0;
}

div.right_eye {
    right: 0;
}

div.eyes div.pupil {
    left: 17px;
    top: 17px;
    width: 25px;
    height: 25px;
    position: relative;
    background-image: url("/img/pupil.png");
    background-repeat: no-repeat;
    background-position: center center;         
}

#circular div.left_eye,
#circular div.right_eye {
    background-image: url("/img/circle.png");
}
```

**Comment by willbrett-design** [comment]
so tried adding it to a blank project and it worked. So I think it muse not be working because I have some other JQuery stuff on my site that is interfering with it.

**Comment by jfmdev** [comment]
Hi, I copied your code in JSFiddle (https://jsfiddle.net/b10Ln93b/) and it seems to work fine.
In the code that you posted, the only error that I can see is that you include both **jqeyes.js** and **jqeyes.min.js** and you only need to include one of them.
Without having access to your HTML file, there is not much else I can do. Have you verified the browser's console in order to see if some JavaScript's exception is generated?

**Comment by willbrett-design** [comment]
Thank you for replying. I am using this as the core template for my site http://startbootstrap.com/template-overviews/freelancer/

I just cant get it to work with the JQEye, im wondering if one of the JS scripts that comes with the template is interfering with the JQEye scripts.

**Comment by willbrett-design** [comment]
I had another go and checked the console in chrome and I'm getting this error:

Uncaught TypeError: jQuery(...).jqEye is not a function

The error is pointing at this line:

jQuery("#circular div.pupil").jqEye({shape: "circle", radius:12});

Not sure how to fix this as Im pretty new to jQuery

**Comment by willbrett-design** [comment]
Figured it out. Issue was that the template was already loading jquery but it was doing it at the bottom of the html page, by moving all the eyeJava script stuff bellow this got it working however the eyes arent following the mouse correctly. Think this might be an issue with bootstrap but unsure. Either way it's not working and my javascript knowledge has been exhausted. 

Great plugin and thank you for sharing.

**Comment by jfmdev** [comment]
Hi. The error that you describes (the eyes not following the mouse correctly) was fixed a few months ago, so you probably are using an old version of the plugin.
If you download the last version (the version 1.02) the error is going to disappear.
